---
abstract: 'easy database connections for Dancer2 applications'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Database
no_index:
  directory:
    - t
    - inc
requires:
  Dancer2: 0.06
  Dancer::Plugin::Database::Core: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/bigpresh/Dancer-Plugin-Database/issues
  homepage: https://github.com/bigpresh/Dancer-Plugin-Database/
  repository: https://github.com/bigpresh/Dancer-Plugin-Database
version: 2.07
